# docker compose file for the project with three services

version: '3.7'
services:
  hadesAPI:
    image: ghcr.io/ls1intum/hades/hades-api
    build:
      context: .
      dockerfile: ./HadesAPI/Dockerfile
    ports:
      # Set the Port to 8081 to avoid conflicts with the artemis server
      - "8081:8080"
    networks:
      - hades
    depends_on:
      nats:
        condition: service_healthy
    environment:
      - NATS_URL=nats://nats:4222

  hadesScheduler:
    image: ghcr.io/ls1intum/hades/hades-scheduler
    build:
      context: .
      dockerfile: ./HadesScheduler/Dockerfile
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - hades
    depends_on:
      nats:
        condition: service_healthy
      hadesAPI:
        condition: service_started
    environment:
      - NATS_URL=nats://nats:4222
      - HADES_EXECUTOR=docker
    
  hadesLogManager:
    image: ghcr.io/ls1intum/hades/hades-log-manager
    build:
      context: .
      dockerfile: ./HadesLogManager/Dockerfile
    ports:
      - "8083:8081"  # Map to 8083 to avoid conflicts
    networks:
      - hades
    depends_on:
      nats:
        condition: service_healthy
      hadesAPI:
        condition: service_started
    environment:
      - HADESLOGMANAGER_API_PORT=8081
      - API_ENDPOINT=${API_ENDPOINT}

  hadesArtemisAdapter:
    image: ghcr.io/ls1intum/hades/hades-artemis-adapter
    build:
      context: .
      dockerfile: ./HadesArtemisAdapter/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - hades
    environment:
      - HADESADAPTER_API_PORT=8082
      - ARTEMIS_BASE_URL=${ARTEMIS_BASE_URL}
      - ARTEMIS_NEW_RESULT_ENDPOINT=${ARTEMIS_NEW_RESULT_ENDPOINT}
      - ARTEMIS_AUTH_TOKEN=${ARTEMIS_AUTH_TOKEN}

  nats:
    image: nats:2.11.4
    command: ["-js", "-m", "8222"]
    networks:
      - hades
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD", "nats-server", "--health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  hades:
