
version: '3.7'
services:
  hadesScheduler:
    environment:
      - NATS_URL=nats://nats:4222
      - KUBECONFIG=/root/.kube/config
      - HADES_EXECUTOR=k8s
    volumes:
      # Adjust this to the path of your kubeconfig file
      - ./.kube/config:/root/.kube/config
